# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f47aacc1f45f4b010a6fa4276c98f5146fe13e8d7851c0a7763123db88af6d8416e006b282f23b40c4947c279eeef6cc60e946e4fb299660237eda8533479f75

test:
  secret_key_base: 22b45fd59f57e8981e7cb63a39bbe4263f48aeca11c179a977076fa54c89a86d1cff2289eb6fb9060e2072029aa699f45a0cc386fc0ca58053c8b0dfab74e557

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
